function H = compute_homography_naive(mp_src, mp_dst)
x = mp_src(1,:);    xp = mp_dst(1,:);
y = mp_src(2,:);    yp = mp_dst(2,:);
N = length(x);  % num of marked points
A = [];
for lag = 1:N
    r1 = [  -x(lag)...
            -y(lag)...
            -1 ...
            0 ...
            0 ...
            0 ...
            xp(lag) * x(lag) ...
            xp(lag) * y(lag) ...
            xp(lag) * 1 ...
            ];
    r2 = [  0 ...
            0 ...
            0 ...
            -x(lag) ...
            -y(lag) ...
            -1 ...
            yp(lag) * x(lag) ...
            yp(lag) * y(lag) ...
            yp(lag) * 1 ...
            ];
    A = [A;r1;r2];
end

[~,~,V] = svd(A);
H = V(:,end);
H = reshape(H, [3 3])';
end
